//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILHAudit: IEntity
    {
        public int ILHAuditId { get; set; }
        public int ProcessRunId { get; set; }
        public int DealerId { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
