//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log: IEntity
    {
        public int LogID { get; set; }
        public int LogTypeID { get; set; }
        public int ProcessRunID { get; set; }
        public string Source { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public System.DateTime LogDate { get; set; }
    
        public virtual LogType LogType { get; set; }
        public virtual ProcessRun ProcessRun { get; set; }
    }
}
